title: Andreas Mang
description: Associate Professor, Department of Mathematics, University of Houston
url: "https://andreasmang.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
